# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Wpedantic -Wconversion -Werror -g

# Source and object files
SRC = main.c \
      src/handle_error.c \
      src/xmalloc.c

OBJ = $(SRC:.c=.o)
TARGET = xmalloc

# Build target
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# Compile .c to .o (automatic dependency generation)
%.o: %.c
	$(CC) $(CFLAGS) -MMD -c $< -o $@

# Include dependency files generated by -MMD
-include $(OBJ:.o=.d)

# Clean object files, dependency files, and binary
clean:
	rm -f $(OBJ) $(OBJ:.o=.d)

